# Generated by Django 3.0.2 on 2020-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='描述'),
        ),
    ]
