# Generated by Django 3.0.2 on 2020-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200306_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%y/%m', verbose_name='头像'),
        ),
    ]
