# Generated by Django 3.0.2 on 2020-03-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
