# Generated by Django 3.0.2 on 2020-03-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(default='基础知识学习', max_length=20, verbose_name='课程标签'),
        ),
    ]
